[package]
name = "objmc"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "objmc-cli"
]

[dependencies]
image = "0.25.5"
serde_json = "1.0.133"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
